[sources.caddy]
type = "file"
include = ["/var/log/caddy/access.log"]
read_from = "beginning"

[transforms.parse]
type = "remap"
inputs = ["caddy"]
source = '''
  . = parse_json!(.message)
  .host = .request.host
  .bytes = to_int(.size) ?? 0
'''

[transforms.filter_valid]
type = "filter"
inputs = ["parse"]
condition = 'exists(.host) && .host != null'

[sinks.express]
type = "http"
inputs = ["filter_valid"]
uri = "http://express_app:3000/internal/log"
encoding.codec = "json"
batch.timeout_secs = 15
batch.max_bytes = 5000000
batch.max_events = 50000
